BoxLayout:

    WindowManager:
        id: screen_manager
        StartWindow:
        ScoreWindow:
        GameWindow:

<Pipe>:
    bottom_body_position: self.pos[1]
    bottom_cap_position: self.pipe_center - self.GAP_SIZE/2.0 - self.CAP_SIZE
    top_cap_position: self.pipe_center + self.GAP_SIZE/2.0
    top_body_position: self.pipe_center + self.GAP_SIZE/2.0 + self.CAP_SIZE

    canvas.before:
        Rectangle:
            # Bottom pipe body
            size: 48, self.bottom_cap_position - self.bottom_body_position
            pos: self.pos[0] + (64 - 48)/2.0, self.bottom_body_position
            texture: self.pipe_body_texture
            tex_coords: self.lower_pipe_tex_coords
        Rectangle:
            # Bottom pipe cap
            size: 64, self.CAP_SIZE
            pos: self.pos[0], self.bottom_cap_position
            source: "pipe_cap.png"

        Rectangle:
            # Top pipe cap
            size: 64, self.CAP_SIZE
            pos: self.pos[0], self.top_cap_position
            source: "pipe_cap.png"
        Rectangle:
            size: 48, self.top - self.top_body_position
            pos: self.pos[0] + (64-48)/2.0, self.top_body_position
            texture: self.pipe_body_texture
            tex_coords: self.top_pipe_tex_coords    

<CustGrid@GridLayout>
    size_hint_y: None
    height: self.minimum_height
    row_default_height: '40dp'
    row_force_default: True
    cols: 1 # Este valor se ajustará en el código Python

<CustButton@Button>
    font_size: 32
    background_color: 0,0,0,0
    canvas.before:
        Color:
            rgba: (0,176/255,1,1) if self.state=='normal' else (0,0,0,1)  # visual feedback of press
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [50,]

<CustHeadLabel@Label>
    font_size: 50
    bold: True
    #font_name: "Comic"
    #color: 1, 1, 1, 1   


<StartWindow>
    name: 'StartWindow'

    BoxLayout:

        orientation: 'vertical'
        size: root.width, root.height
        spacing: '20dp'
        padding: ('20dp', '20dp', '20dp', '20dp')
        
        Label:
            text: 'BIRD GAME'
            font_size: 40
            bold: True
            #font_name: "Comic"
            color: 1, 1, 1, 1
            #background_color: 255/255, 75.3/255, 79.6/255

        CustButton:
            text: 'Go Game'
            on_release:
                app.root.ids.screen_manager.current = 'GameWindow'
                root.manager.transition.direction = 'up'



<ScoreWindow>
    name: 'ScoreWindow'
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        padding: ('20dp', '20dp', '20dp', '20dp')
        
        CustHeadLabel:
            text: 'Unidades'
            size_hint: 1,.1

        CustGrid:
            id: header_layout

        ScrollView:
            do_scroll_x: False
            do_scroll_y: True

            CustGrid:
                id: table_layout


        CustButton:
            text: 'BACK'
            # font_size: 32
            size_hint: .5,.2
            pos_hint: {'center_x': .5}
            on_release:
                app.root.ids.screen_manager.current = 'GameWindow'
                root.manager.transition.direction = 'down'

<GameWindow>:
    name: 'GameWindow'
    FloatLayout:
        Background:
            id: background
            canvas.before:
                Rectangle:
                    size: self.size
                    pos: self.pos
                    source: "sky.png"
                Rectangle:
                    size: self.width, 138
                    pos: self.pos[0], self.pos[1] + self.height - 138
                    texture: self.cloud_texture
                Rectangle:
                    size: self.width, 96
                    pos: self.pos[0], self.pos[1]
                    texture: self.floor_texture
        Label:
            id: score
            # size_hint_y: None
            # height: 96
            text: "0"
            font_size: 40
            pos_hint: {"x":.4, "y":-.445}
            # pos: (200, -250)
        Button:
            id: lvl_1
            text:'Easy'
            # size_hint_x: .1
            # size_hint_y: .1
            size: 60, 40
            size_hint: None, None
            pos_hint: {"x":.025, "y":.05}
            on_release: 
                # self.disabled = False
                # self.opacity = 0
                root.pipe_deviation_easy()
        Button:
            id: lvl_2
            text:'Normal'
            size: 60, 40
            size_hint: None, None
            pos_hint: {"x":.125, "y":.05}
            on_release:
                root.pipe_deviation_med()
        Button:
            id: lvl_3
            text:'Hard'
            size: 60, 40
            size_hint: None, None
            pos_hint: {"x":.225, "y":.05}
            on_release:
                root.pipe_deviation_hard()
        Button:
            text: "Start game"
            background_normal: "transparent.png"
            background_down: "transparent.png"
            id: start_button
            pos_hint: {"x":0,"top":1}
            size_hint: 1, .8
            on_release:
                self.disabled = True
                self.opacity = 0
                root.start_game()
        Bird:
            source: "bird1.png"
            size_hint: None, None
            size: 46, 34
            pos: 20, (root.height - 96) / 2.0
            id: bird