ScreenManager:
    id: screen_manager
    ScoreWindow:
        name: 'ScoreWindow'
    GameWindow:
        name: 'GameWindow'

<Pipe>:
    bottom_body_position: self.pos[1]
    bottom_cap_position: self.pipe_center - self.GAP_SIZE/2.0 - self.CAP_SIZE
    top_cap_position: self.pipe_center + self.GAP_SIZE/2.0
    top_body_position: self.pipe_center + self.GAP_SIZE/2.0 + self.CAP_SIZE

    canvas.before:
        Rectangle:
            # Bottom pipe body
            size: 48, self.bottom_cap_position - self.bottom_body_position
            pos: self.pos[0] + (64 - 48)/2.0, self.bottom_body_position
            texture: self.pipe_body_texture
            tex_coords: self.lower_pipe_tex_coords
        Rectangle:
            # Bottom pipe cap
            size: 64, self.CAP_SIZE
            pos: self.pos[0], self.bottom_cap_position
            source: "pipe_cap.png"

        Rectangle:
            # Top pipe cap
            size: 64, self.CAP_SIZE
            pos: self.pos[0], self.top_cap_position
            source: "pipe_cap.png"
        Rectangle:
            size: 48, self.top - self.top_body_position
            pos: self.pos[0] + (64-48)/2.0, self.top_body_position
            texture: self.pipe_body_texture
            tex_coords: self.top_pipe_tex_coords

<GameWindow>:

    FloatLayout:
        Background:
            id: background
            canvas.before:
                Rectangle:
                    size: self.size
                    pos: self.pos
                    source: "sky.png"
                Rectangle:
                    size: self.width, 138
                    pos: self.pos[0], self.pos[1] + self.height - 138
                    texture: self.cloud_texture
                Rectangle:
                    size: self.width, 96
                    pos: self.pos[0], self.pos[1]
                    texture: self.floor_texture
        Label:
            id: score
            # size_hint_y: None
            # height: 96
            text: "0"
            font_size: 40
            pos_hint: {"x":.4, "y":-.445}
            # pos: (200, -250)
        Button:
            id: lvl_1
            text:'Easy'
            # size_hint_x: .1
            # size_hint_y: .1
            size: 60, 40
            size_hint: None, None
            pos_hint: {"x":.025, "y":.05}
            on_release: 
                # self.disabled = False
                # self.opacity = 0
                app.pipe_deviation_easy()
        Button:
            id: lvl_2
            text:'Normal'
            size: 60, 40
            size_hint: None, None
            pos_hint: {"x":.125, "y":.05}
            on_release:
                app.pipe_deviation_med()
        Button:
            id: lvl_3
            text:'Hard'
            size: 60, 40
            size_hint: None, None
            pos_hint: {"x":.225, "y":.05}
            on_release:
                app.pipe_deviation_hard()
        Button:
            text: "Start game"
            background_normal: "transparent.png"
            background_down: "transparent.png"
            id: start_button
            pos_hint: {"x":0,"top":1}
            size_hint: 1, .8
            on_release:
                self.disabled = True
                self.opacity = 0
                root.start_game()
        Bird:
            source: "bird1.png"
            size_hint: None, None
            size: 46, 34
            pos: 20, (root.height - 96) / 2.0
            id: bird

<CustHeadLabel@Label>
    font_size: 50
    bold: True

<CustGrid@GridLayout>
    size_hint_y: None
    height: self.minimum_height
    row_default_height: '40dp'
    row_force_default: True
    cols: 2 # Este valor se ajustará en el código Python

<ScoreWindow>
 
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        padding: ('20dp', '20dp', '20dp', '20dp')
        
        CustHeadLabel:
            text: 'GAME SCORES'
            size_hint: 1,.1

        CustGrid:
            id: score_header

        ScrollView:
            do_scroll_x: False
            do_scroll_y: True

            CustGrid:
                id: score_table
        
        Button:
            text: 'GAME'
            size_hint: 1,.1
            on_release:
                app.root.current = 'GameWindow'
                root.manager.transition.direction = 'right'
   
    


        
