<Button>:
    color: .8,.9,0,1
    font_size: 32
     
<MiWidget>:

    orientation: 'rl-tb'
    padding: 10
    Button:  
        text: "Link 1..."
        size_hint: [.7, .2] 
    Button:
        text: "Link 2..."
        size_hint: [.3, .3] 
    Button:
        text: "Link 3..." 
        size_hint: [.3, .2]         
    Button:
        text: "Link 4..." 
        size_hint: [.3, .3]         

    
    
    
