<MainWindow>:
    FloatLayout:
        #orientation: 'vertical'
        # Label:
        #     text: 'Ventana Principal'
        Button:
            text: 'Ir a la segunda ventana'
            on_press: app.switch_to_second

<SecondWindow>:
    FloatLayout:
    #orientation: 'vertical'
    # Label:
    #     text: 'Segunda Ventana'
        Button:
            text: 'Volver a la ventana principal'
            on_press: app.switch_to_main
